# Generated by Django 6.0.1 on 2026-01-31 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_payment_stripe_checkout_session_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method',
        ),
    ]
