# Generated by Django 6.0.1 on 2026-02-04 09:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0004_remove_payment_transaction_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='gateway_response',
        ),
    ]
