# Generated by Django 6.0.1 on 2026-02-09 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='content_picture_url',
            field=models.URLField(default='https://via.placeholder.com/150'),
        ),
    ]
